#! /bin/sh

sxhkd &
xsetroot -cursor_name GoogleDot-black &
flameshot &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore & 
picom --config $HOME/.config/picom.conf &
sh $HOME/.config/polybar/launch.sh &
# setxkbmap -layout us,ru -option "grp:alt_shift_toggle" &
setxkbmap -layout us,ru -option "grp:caps_toggle" &
xinput set-prop 14 324 0.7 &
dunst &
xfce4-power-manager &

bspc monitor -d         
# bspc monitor -d term web files soc music docs mult sett code

bspc config border_width         0
bspc config window_gap          17
bspc config -m HDMI-1 top_padding  0
bspc config focused_border_color \#f5c2e7
bspc config urgent_border_color \#E8A2AF
bspc config normal_border_color \#1e1e2e
bspc config active_border_color \#1e1e2e

bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kitty desktop='^1'
bspc rule -a Alacritty desktop='^1'
bspc rule -a Chromium desktop='^2' state=monocle
bspc rule -a Firefox-esr desktop='^2' state=monocle
bspc rule -a Spotify desktop='^5'
bspc rule -a Nitrogen desktop='^8'
bspc rule -a Thunar desktop='^3'
bspc rule -a Nautilus desktop='^3'
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a discord desktop='^4'
bspc rule -a libreoffice* desktop='^6'
bspc rule -a feh desktop='^7' state=floating
bspc rule -a OpenComic desktop='^7'
bspc rule -a Audacity desktop='^7'
bspc rule -a Gimp* desktop='^7'
bspc rule -a Lxappearance desktop='^8'
bspc rule -a Lightdm-gtk-greeter-settings desktop='^8'
bspc rule -a Pavucontrol desktop='^8'
bspc rule -a GParted desktop='^8'
bspc rule -a Code desktop='^9'
bspc rule -a mpv desktop='^7'
